* Marcas importantes
** Número IMO
*** ¿Qué es?
Es el identificador único reconocido mundialmente para los barcos pesqueros.
Nunca es reutilizado y acompaña al barco durante toda su vida.
*** ¿Cómo es?
Es un número de 7 dígitos.
*** ¿Dónde está?
En la popa o en el casco o superestructura
** Indicativo internacional de llamada de radio (IRCS)
*** ¿Qué es?
Es el identificador único del equipo de radio a bordo. Aunque puede cambiar
durante la vida útil del barco nunca estará asociado a dos barcos al mismo tiempo.
*** ¿Cómo es?
Una combinación de letras y números. Los dos o tres primeros caracteres
corresponden al país. Normalmente se marcan en negro sobre fondo blanco o blanco
sobre fondo negro. Debería ser la única marca que combine letras y números.
*** ¿Dónde está?
En los lados de babor y estribor del casco del barco. También debería
encontrarse en el resto de embarcaciones transportadas por el buque.

* Actividades sospechosas
El fallo en mantener adecuadamente el marcado de los barcos, puede ser
simplemente un descuido. Sin embargo, pueden indicar también, que un operador
está deliberadamente escondiendo, o confundiendo la identidad del barco pesquero
para cometer actividades de pesca ilegal.

Es importante reportar las siguientes malas prácticas para aumentar la
vigilancia de las autoridades ante un barco de riesgo alto:

- Esconder las marcas mediante artes de pesca o lonas
- Múltiples nombres, múltiples indicativos de llamada o puertos
- Puerto e indicativo de llamada asociado a mas de un pabellón
- Marcas fácilmente desmontables, como en tablas
- Marcas manipuladas

* Toma de fotografías
Elementos a intentar capturar en las fotografías:
- Marcas de identificación en general. Especialmente IMO e Identificativo de
  llamada
- Intentos de ocultar sus marcas
- Caracteres chinos, debido a su dificil lectura
- Aperos de pesca
- Logotipos
- Elementos estructurales del buque (puente, huecos en el casco...)
