* Overview

#+begin_src plantuml :file components-app.png
  @startuml
  !includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Component.puml
  ' uncomment the following line and comment the first to use locally
  ' !include C4_Component.puml
  'LAYOUT_TOP_DOWN
  'LAYOUT_WITH_LEGEND

  title Component diagram for IUU Fishing Capture System - Mobile App

  Person(informer, "Informer", "A suspicious vessel activity informer")
  Component(mod, "Moderation Context", "", "This context analyse, enrich, complete and filter received reports")
  Component(pub, "Publishing context", "", "Store and host reports, anonymize them and prepare to be shared as datasets, public images, facebook cards...")
  System_Ext(gfw, "Global Fishing Watch", "Share AIS-based information, for instance: risk index")
  System_Ext(vms, "National VMS public data", "Store a historical VMS position datasets which can be used to verify or trust reports")

  Container_Boundary(app, "Mobile App") {
          Component(report, "Report Context", "", "Create and send upstream suspicious activity report")
          Component(area, "Fishing Area Context", "", "Allows capture system validate and enrich position")
          Component(vessel, "Vessel Identification Context", "", "Capture information about the suspicious vessel")
          Component(informerdata, "Informer Data Context", "", "Enrich report with informer own data")
          Component(help, "Help Context", "", "Helps users to learn about legal concerns and vessels markings")

          Rel(area, report, "Fishing Area detected")
          Rel(vessel, report, "Suspicious Vessel identified")
          Rel(informerdata, report, "Informer Data introduced")
          Rel(help, vessel, " ")
          Rel(help, informerdata, " ")
  }

  Rel(informer, area, "Suspicious Vessel encountered")
  Rel(report, mod, "Unmoderated Report")
  Rel(report, pub, "Unmoderated Report")
  Rel_L(mod, pub, "Moderated Report")
  Rel(mod, gfw, "Get data")
  Rel(mod, vms, "Get data")
  @enduml
#+end_src

* Report Context
** Overview
La flota pesquera artesanal denuncia que se producen encuentros en alta mar con
embarcaciones sospechosas de ejercer pesca ilegal. Principalmente flota de
bandera asiática. Carecen de herramientas específicas que les permitan registrar
estos encuentros y no existe un consenso sobre cuál es la información más
valiosa a capturar.

Estos encuentros se producen generalmente en zonas fuera de cobertura móvil y la
estancia en esas zonas puede durar hasta 8 días.

** data
#+BEGIN_SRC
data Report =
  FishingVessel
  AND NoEmptyList of SuspiciousActivity
  AND InformerData
#+END_SRC
** workflows
#+BEGIN_SRC
workflow "ReportSuspiciousActivity" =
  input = EmptyReport
  output (on success) = SuspiciousActivityReported
  output (on error) = InvalidReport

//step 1
do CheckFields
#+END_SRC

* Fishing Area Context
** Overview
El proyecto va dirigido al ámbito de Calamasur. Los límites de las zonas
económicas exclusivas (EEZ) donde se producen el mayor número de encuentros
están definidos y aceptados internacionalmente.

Otras zonas de pesca tendrán problemas que serán total o sutilmente diferentes a
los de Calamasur, y sobre los que SFP no tiene actualmente acuerdos o competencias.
No es descartable que en futuras versiones se de soporte a estos otros problemas.

Todos los dispositivos son capaces de obtener su geolocalización.

*** Goals
- Mejorar la experiencia de usuario con una interfaz y reglas de negocio
  adaptadas a la localización.
- Comprobar que las capacidades de localización del dispositivo están encendidas.
- Garantizar que al comienzo del proceso tenemos una posición minimamente
  precisa.
- Minimizar el número de informes no válidos que moderar (Desde tierra, zonas
  sin competencias...)

** data
#+BEGIN_SRC
data DeviceLocationData =
  Latitude
  AND Longitude
  AND Accurancy

data DesiredAccurancy =
  Meters

data GetFishingAreaInput =
  DeviceLocationData
  AND DesiredAccurancy

data AccurateLocation =
  AccurateLatitude
  AND AccurateLongitude

data SupportedAreas =
  list of SupportedArea

data SupportedArea =
  FishingAreaName
  AND PolygonArea // As in marineregions.org

data SupportedFishingArea =
  CalamasurArea
  OR GenericArea
  OR ...
#+END_SRC

** workflows
#+BEGIN_SRC
workflow "GetFishingArea" =
  input: GetFishingAreaInput
  output (on success): SupportedFishingAreaDetected
  output (on error): UnsupportedFishingArea OR InaccurateLocation

//step1
do CheckLocationAccurancy
  If inaccurate
  return InaccurateLocation
  stop

//step2
do CheckPosition
  If unsupported
  return UnsupportedFishingArea
  stop

//step3
return SupportedFishingAreaDetected
#+END_SRC

*** substeps
#+BEGIN_SRC
substep "CheckLocationAccuracy" =
  input: GetFishingAreaInput
  output (on success): AccurateLocation
  output (on error): InaccurateLocation

substep "CheckPosition" =
  input: AccurateLocation
  dependency: SupportedAreas
  output (on sucess): SupportedFishingArea
  output (on error): UnsupportedFishingArea
#+END_SRC
* Vessel Identification Context
** Overview
En Calamasur las embarcaciones sospechosas de ejercer pesca ilegal son
principalmente de bandera asiática.

Puede ser particularmente difícil identificar los barcos asiáticos por sus
nombres, ya que existe una gran variación en la forma en que se escriben los
caracteres chinos en letras romanas, por lo que capturar cualquier número
visible en el casco es particularmente importante.

Hay diversidad de opiniones respecto a la cercanía de los encuentros y la
capacidad de poder capturar información relevante con el dispositivo móvil. Sin
embargo parece unánime que los buques sospechosos suelen estar muy sucios,
nombre ilegible o intentos de ocultar sus marcas.

Según FAO los intentos de ocultar sus marcas son en si mismo un motivo de denuncia,
independientemente de la actividad pesquera que estén ejerciendo. Lo mismo para
marcas duplicadas, o navegar sin bandera.

Las embarcaciones sospechosas ejercen una actividad industrial, por lo que estan
obligados a emitir por el sistema de radio AIS. Sin embargo las embarcaciones
artesanas de Calamasur en su mayoría no disponen de receptores AIS. Si disponen
de AIS las flotas industriales de la zona.

*** Goals
- Obtener la información mas relevante posible
- Obtener avisos aun sin información relevante
- Educar sobre los diferentes hechos denunciables, mas alla de la actividad
  pesquera.
- Tratar de obtener pruebas gráficas, aun de calidad baja, donde se capturen
  detalles de la construcción de los buques.
- Llegar a conocer si el sistema AIS está apagado o enviando datos falsos (spoofing).
** Design trade-offs

TODO: número de fotos permitidas
TODO: número de vídeos

** data
#+BEGIN_SRC
// Markings
data IMONumber =
  string 9 numbers

data CallSign =
  string first 3 chars as ITU codes

data Other =
  string

data Marking <a> =
  <a>
  OR <a> MarkingNotVisibleOrHidden

data Markings =
  Marking<CallSign>
  AND Marking<IMONumber>
  AND list of Marking<Others>


// AIS Transmission
data MMSI =
  string 7 numbers

data AISDeclaredActivity =
  Fishing
  OR ToPort
  OR ...

data AISTransmission =
  MMSI
  AND AISCallSign
  AND AISName
  AND AISDeclaredActivity


// Vessel
data FishingVessel =
  Type
  AND Markings
  AND AISTransmission
  AND list of Photos

// Activity
data SuspiciousActivity =
  EEZFishingActivity
  OR HiddingMarkings
  OR DuplicatedMarkings
  OR SignsOfTampering
  OR Stateless
  OR NotAISSignal
  OR AISSpoofedSignal
  OR Other
#+END_SRC
* Informer Data Context
** Overview
El usuario o informador será generalmente un patrón de embarcación de pesca
artesanal. Suele ser reticente a desvelar su identidad o a hacer pública la
posición geográfica exacta del encuentro.

La flota artesanal carece de transmisores AIS, pero está en plena implantación
del sistema VMS. La flota industrial si transmite AIS públicamente.

Los dispositivos móviles Android que utilizan permiten obtener, no sólo la
posición, si no también volcados raw de la información de los sistemas de
navegación.

*** Goals
- Extraer el máximo contexto posible del momento de la captura
- Tener la información necesaria para poder dar veracidad al encuentro
  basándonos en las señales AIS, VMS de la embarcación
- Extraer los datos necesarios para poder valorar la calidad técnica de la señal
  GNSS del dispositivo móvil.

** data
#+BEGIN_SRC
data PeruvianVMSIdentifier =
  String as "P-04-00951"

data ChileanVMSIdentifier =
  VesselName

data VMSIdentifier =
  PeruvianVMSId
  OR ChileanVMSId

data InformerDeviceLocation =
  RawGNSSMeasurementsDump
  OR BasicLocation

data InformerAIS =
  MMSINumber
  OR WithoutOrPrivateAIS

data InformerVMS =
  VMSIdentifier
  OR WithoutOrPrivateVMS

data InformerData =
  InformerVMS
  AND InformerAIS
  AND InformerDeviceLocation
#+END_SRC

* Help Context
** Overview
El conocimiento de la legislación por los patrones o usuarios de la aplicación
es bajo. Igualmente lo referido a los sistemas de marcado o de radio
internacionales para flotas industriales.

Las especificaciones técnicas de las cámaras de los dispositivos móviles son
bajas, así como las oportunidades de obtener buenas tomas por distancia,
movimientos, suciedad de las embarcaciones...

*** Goals
- Educar a los usuarios sobre qué marcas del casco o del puente son importantes
  en la identifiación de un barco.
- Informar de la localización mas común de las marcas.
- Informar sobre los detalles constructivos que son mas sencillos de
  fotografiar.
- Educar sobre las trasngresiones mas habituales en las flotas ilegales.


#+BEGIN_SRC
data MarkingsHelp =
  Name
  AND Description
  AND list of Examples
  AND list of TypicalLocation
  AND list of ExamplePhotos

data TypicalLocation =
  Stern
  OR Side
  OR Bridge
#+END_SRC

* Scratch

Si hay una foto general del barco abre la puerta apoder incorporar fotos tomadas
con alguna cámara externa. Si no hay niguna es imposible verificar que
corresponda con el mismo encuentro.

No debo mezclar la definición del barco, los facts, con el estado en el momento
de la captura. Tratar de ocultar una marca, o estar realizando pesca ilegal, es
estado. Pero por ejemplo, tener callsign duplicados? es estado o hechos?

